"""Project-wide constants and defaults."""

# Currency
DEFAULT_FX_USD_TO_LKR = 375.0

# Time
HOURS_PER_YEAR = 8760.0
DAYS_PER_YEAR = 365.0

# Project defaults
DEFAULT_PROJECT_LIFE_YEARS = 20
DEFAULT_CAPACITY_FACTOR = 0.35
DEFAULT_DEGRADATION = 0.005

# Financial defaults
DEFAULT_DISCOUNT_RATE = 0.08
DEFAULT_DSCR_THRESHOLD = 1.25
DEFAULT_DEBT_RATIO = 0.70
DEFAULT_TENOR_YEARS = 15

# Validation
MIN_CAPACITY_MW = 1.0
MAX_CAPACITY_MW = 1000.0
MIN_CAPACITY_FACTOR = 0.10
MAX_CAPACITY_FACTOR = 0.60
