#!/usr/bin/env python
"""Generate the package-level architecture diagram from the ACTUAL import graph.

The diagram in ``docs/architecture_import_graph.mmd`` is derived, not drawn: this
script walks every first-party source package, parses each module with :mod:`ast`,
and records an edge ``A --> B`` whenever a module in package ``A`` imports package
``B``. Emitting from the real imports means the picture cannot silently drift from
the code the way a hand-maintained diagram does (the risk ``docs/ARCHITECTURE.md``
itself warns about).

Node set is auto-discovered (every top-level directory that is an importable
package), so adding or removing a package updates the diagram on the next run
rather than requiring a manual edit.

Usage:
    python scripts/gen_architecture_diagram.py            # regenerate the .mmd
    python scripts/gen_architecture_diagram.py --check    # fail if it is stale

``--check`` regenerates in memory and compares to the committed file, exiting
non-zero on any difference. A test wires this into CI so the diagram stays
honest (see ``tests/docs/test_architecture_diagram.py``).
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "docs" / "architecture_import_graph.mmd"
ARCH_DOC = REPO_ROOT / "docs" / "ARCHITECTURE.md"

# The generated Mermaid block is spliced into ARCHITECTURE.md between these
# markers so the rendered-on-GitHub copy can never drift from the .mmd artifact.
_BEGIN_MARKER = "<!-- BEGIN-GENERATED-IMPORT-GRAPH -->"
_END_MARKER = "<!-- END-GENERATED-IMPORT-GRAPH -->"

# Directories that are never graph nodes even if they contain an __init__.py.
_EXCLUDE_DIRS = frozenset(
    {
        "tests",
        "legacy",
        "legacy_scenarios",
        "examples",
        "scripts",
        "conf",
        "config",
        "docs",
        "build",
        "dist",
    }
)


def _discover_packages(root: Path) -> list[str]:
    """Return the sorted names of first-party importable top-level packages.

    A top-level directory counts as a package node when it contains an
    ``__init__.py`` and is not an excluded/tooling/vendored directory.
    """
    packages: list[str] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        name = child.name
        if name.startswith(".") or name.startswith("_"):
            continue
        if name in _EXCLUDE_DIRS or name.endswith(".egg-info"):
            continue
        if (child / "__init__.py").exists():
            packages.append(name)
    return packages


def _top_level(module: str | None) -> str | None:
    """Return the top-level package of a dotted ``module`` path, or ``None``."""
    if not module:
        return None
    return module.split(".", 1)[0]


def _imports_of(py_file: Path) -> set[str]:
    """Parse ``py_file`` and return the set of top-level modules it imports."""
    try:
        tree = ast.parse(py_file.read_text(encoding="utf-8"), filename=str(py_file))
    except (SyntaxError, UnicodeDecodeError):
        return set()
    tops: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = _top_level(alias.name)
                if top:
                    tops.add(top)
        elif isinstance(node, ast.ImportFrom):
            # Ignore relative imports (level > 0): they stay within the package.
            if node.level == 0:
                top = _top_level(node.module)
                if top:
                    tops.add(top)
    return tops


def build_edges(root: Path, packages: list[str]) -> dict[str, set[str]]:
    """Return ``{package: {imported first-party packages}}`` (self-edges dropped)."""
    pkg_set = set(packages)
    edges: dict[str, set[str]] = {pkg: set() for pkg in packages}
    for pkg in packages:
        for py_file in sorted((root / pkg).rglob("*.py")):
            for imported in _imports_of(py_file):
                if imported in pkg_set and imported != pkg:
                    edges[pkg].add(imported)
    return edges


def render_mermaid(packages: list[str], edges: dict[str, set[str]]) -> str:
    """Render the package graph as a deterministic Mermaid ``flowchart``."""
    lines = [
        "%% AUTO-GENERATED by scripts/gen_architecture_diagram.py — do not edit by hand.",
        "%% Regenerate with: python scripts/gen_architecture_diagram.py",
        "%% Each edge A --> B means a module in package A imports package B.",
        "flowchart LR",
    ]
    for pkg in packages:
        lines.append(f"    {pkg}[{pkg}]")
    for pkg in packages:
        for target in sorted(edges[pkg]):
            lines.append(f"    {pkg} --> {target}")
    return "\n".join(lines) + "\n"


def generate(root: Path = REPO_ROOT) -> str:
    """Build the Mermaid diagram text from the live import graph under ``root``."""
    packages = _discover_packages(root)
    edges = build_edges(root, packages)
    return render_mermaid(packages, edges)


def _splice_into_arch_doc(doc: str, mermaid: str) -> str:
    """Return ``doc`` with the fenced Mermaid block between the markers refreshed.

    Raises:
        ValueError: if the begin/end markers are absent or malformed — the doc
            must carry them once (added when this diagram section was created).
    """
    start = doc.find(_BEGIN_MARKER)
    end = doc.find(_END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            f"{ARCH_DOC.relative_to(REPO_ROOT)} is missing the "
            f"{_BEGIN_MARKER} / {_END_MARKER} markers."
        )
    block = f"{_BEGIN_MARKER}\n```mermaid\n{mermaid.rstrip()}\n```\n{_END_MARKER}"
    return doc[:start] + block + doc[end + len(_END_MARKER) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if either generated output differs from a fresh render.",
    )
    args = parser.parse_args(argv)

    rendered = generate()
    arch_doc = ARCH_DOC.read_text(encoding="utf-8")
    arch_updated = _splice_into_arch_doc(arch_doc, rendered)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        stale = []
        if current != rendered:
            stale.append(str(OUTPUT.relative_to(REPO_ROOT)))
        if arch_doc != arch_updated:
            stale.append(str(ARCH_DOC.relative_to(REPO_ROOT)))
        if stale:
            print(
                f"Stale: {', '.join(stale)}. "
                "Run: python scripts/gen_architecture_diagram.py",
                file=sys.stderr,
            )
            return 1
        print("Architecture diagram is up to date.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    ARCH_DOC.write_text(arch_updated, encoding="utf-8")
    print(
        f"Wrote {OUTPUT.relative_to(REPO_ROOT)} "
        f"and refreshed the block in {ARCH_DOC.relative_to(REPO_ROOT)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
