# Auto-generated by scripts/fix_monte_carlo_import_bridge.sh
# Bridge for legacy absolute import:
#   from parameter_validation import validate_project_parameters
try:
    # Preferred: use package validator
    from dutchbay_v13.validate import validate_project_parameters  # type: ignore
except Exception:
    # Fallback no-op validator to avoid hard crashes in smoke/import tests.
    # It simply returns the given params unchanged.
    def validate_project_parameters(params, where=None):  # type: ignore
        return params
